/**
 * Calendário Romano Geral — santos e celebrações litúrgicas de cada dia.
 *
 * Fonte: Calendarium Romanum Generale (revisão 1969, emendas até 2024).
 * Formato: "M-D" → array de nomes a pesquisar no Wikipedia PT (em ordem de prioridade).
 *
 * Usado por santo-dia.js para garantir que o santo exibido seja o do
 * Calendário Romano Geral, e não apenas o do Martyrologium Romanum.
 */
(function () {
    'use strict';

    window.CalendarioRomano = {
        /* ── Janeiro ────────────────────────────────────────── */
        '1-1':  ['Maria Mãe de Deus'],
        '1-2':  ['Basílio Magno', 'Gregório Nazianzeno'],
        '1-4':  ['Isabel Ana Seton'],
        '1-5':  ['João Neumann'],
        '1-6':  ['André Bessette'],
        '1-7':  ['Raimundo de Penhaforte'],
        '1-13': ['Hilário de Poitiers'],
        '1-17': ['Antônio do Deserto'],
        '1-20': ['Fabiano', 'Sebastião mártir'],
        '1-21': ['Inês de Roma'],
        '1-22': ['Vicente de Saragoça'],
        '1-24': ['Francisco de Sales'],
        '1-25': ['Conversão de Paulo'],
        '1-26': ['Timóteo apóstolo', 'Tito apóstolo'],
        '1-27': ['Ângela Mérici'],
        '1-28': ['Tomás de Aquino'],
        '1-31': ['João Bosco'],

        /* ── Fevereiro ──────────────────────────────────────── */
        '2-2':  ['Apresentação do Senhor no Templo'],
        '2-3':  ['Brás de Sebaste', 'Ansa de Milão'],
        '2-5':  ['Ágata de Catânia'],
        '2-6':  ['Paulo Miki'],
        '2-8':  ['Jerônimo Emiliani', 'Josefina Bakhita'],
        '2-10': ['Escolástica de Núrsia'],
        '2-11': ['Nossa Senhora de Lourdes'],
        '2-14': ['Cirilo monge', 'Metódio bispo'],
        '2-17': ['Sete Santos Fundadores dos Servitas'],
        '2-21': ['Pedro Damião'],
        '2-22': ['Cátedra de Pedro'],
        '2-23': ['Policarpo de Esmirna'],

        /* ── Março ──────────────────────────────────────────── */
        '3-4':  ['Casimiro da Polônia'],
        '3-7':  ['Perpétua e Felicidade'],
        '3-8':  ['João de Deus'],
        '3-9':  ['Francisca Romana'],
        '3-17': ['Patrício da Irlanda'],
        '3-18': ['Cirilo de Jerusalém'],
        '3-19': ['José esposo de Maria'],
        '3-23': ['Toríbio de Mogrovejo'],
        '3-25': ['Anunciação do Senhor'],

        /* ── Abril ──────────────────────────────────────────── */
        '4-2':  ['Francisco de Paula'],
        '4-4':  ['Isidoro de Sevilha'],
        '4-5':  ['Vicente Ferrer'],
        '4-7':  ['João Batista de La Salle'],
        '4-11': ['Estanislau de Cracóvia'],
        '4-13': ['Martinho I'],
        '4-21': ['Anselmo de Cantuária'],
        '4-23': ['Jorge mártir'],
        '4-24': ['Fidélis de Sigmaringa'],
        '4-25': ['Marcos evangelista'],
        '4-26': ['Nossa Senhora do Bom Conselho'],
        '4-28': ['Pedro Chanel', 'Luís Maria Grignion de Montfort'],
        '4-29': ['Catarina de Siena'],
        '4-30': ['Pio V'],

        /* ── Maio ───────────────────────────────────────────── */
        '5-1':  ['José Operário'],
        '5-2':  ['Atanásio de Alexandria'],
        '5-3':  ['Filipe apóstolo', 'Tiago apóstolo Alfeu'],
        '5-10': ['João de Ávila', 'Damião de Veuster'],
        '5-12': ['Nereu mártir', 'Aquileu mártir', 'Pancrácio mártir'],
        '5-13': ['Nossa Senhora de Fátima'],
        '5-14': ['Matias apóstolo'],
        '5-15': ['Isidoro Agricultor'],
        '5-18': ['João I papa'],
        '5-20': ['Bernardino de Siena'],
        '5-21': ['Cristóvão Magallanes'],
        '5-22': ['Rita de Cássia'],
        '5-25': ['Beda Venerável', 'Gregório VII', 'Maria Madalena de Pazzi'],
        '5-26': ['Filipe Neri'],
        '5-27': ['Agostinho de Cantuária'],
        '5-31': ['Visitação de Maria'],

        /* ── Junho ──────────────────────────────────────────── */
        '6-1':  ['Justino mártir'],
        '6-2':  ['Marcelino mártir', 'Pedro Exorcista'],
        '6-3':  ['Carlos Lwanga'],
        '6-5':  ['Bonifácio de Maguncia'],
        '6-6':  ['Norberto de Magdeburgo'],
        '6-9':  ['Éfrem o Sírio'],
        '6-11': ['Barnabé apóstolo'],
        '6-13': ['Antônio de Pádua'],
        '6-19': ['Romualdo'],
        '6-21': ['Luís Gonzaga'],
        '6-22': ['Paulino de Nola', 'João Fisher', 'Tomás Moro'],
        '6-24': ['Nascimento de João Batista'],
        '6-27': ['Cirilo de Alexandria'],
        '6-28': ['Ireneu de Lyon'],
        '6-29': ['Pedro apóstolo', 'Paulo apóstolo'],
        '6-30': ['Primeiros Mártires de Roma'],

        /* ── Julho ──────────────────────────────────────────── */
        '7-3':  ['Tomé apóstolo'],
        '7-4':  ['Isabel de Portugal'],
        '7-5':  ['Antônio Maria Zaccaria'],
        '7-6':  ['Maria Goretti'],
        '7-9':  ['Agostinho Zhao Rong'],
        '7-11': ['Bento de Núrsia'],
        '7-13': ['Henrique II da Alemanha'],
        '7-14': ['Camilo de Lélis', 'Kateri Tekakwitha'],
        '7-15': ['Boaventura de Bagnoregio'],
        '7-16': ['Nossa Senhora do Carmo'],
        '7-20': ['Apolinário de Ravena'],
        '7-21': ['Lourenço de Brindisi'],
        '7-22': ['Maria Madalena'],
        '7-23': ['Brígida da Suécia'],
        '7-24': ['Xarbel Makhluf'],
        '7-25': ['Tiago apóstolo'],
        '7-26': ['Joaquim e Ana pais de Maria'],
        '7-29': ['Marta de Betânia'],
        '7-30': ['Pedro Crisólogo'],
        '7-31': ['Inácio de Loyola'],

        /* ── Agosto ─────────────────────────────────────────── */
        '8-1':  ['Afonso de Ligório'],
        '8-2':  ['Eusébio de Vercelli', 'Pedro Julião Eymard'],
        '8-4':  ['João Maria Vianney'],
        '8-5':  ['Nossa Senhora das Neves'],
        '8-6':  ['Transfiguração do Senhor'],
        '8-7':  ['Sisto II papa mártir', 'Caetano de Thiene'],
        '8-8':  ['Domingos de Gusmão'],
        '8-9':  ['Teresa Benedita da Cruz'],
        '8-10': ['Lourenço mártir'],
        '8-11': ['Clara de Assis'],
        '8-12': ['Joana Francisca de Chantal'],
        '8-13': ['Pôntico mártir', 'Hipólito mártir'],
        '8-14': ['Maximiliano Kolbe'],
        '8-15': ['Assunção de Maria'],
        '8-16': ['Estevão da Hungria'],
        '8-19': ['João Eudes'],
        '8-20': ['Bernardo de Claraval'],
        '8-21': ['Pio X'],
        '8-22': ['Maria Rainha'],
        '8-23': ['Rosa de Lima'],
        '8-24': ['Bartolomeu apóstolo'],
        '8-25': ['Luís IX de França', 'José de Calazans'],
        '8-27': ['Mônica de Tagaste'],
        '8-28': ['Agostinho de Hipona'],
        '8-29': ['Martírio de João Batista'],

        /* ── Setembro ───────────────────────────────────────── */
        '9-3':  ['Gregório Magno'],
        '9-8':  ['Natividade de Maria'],
        '9-9':  ['Pedro Claver'],
        '9-13': ['João Crisóstomo'],
        '9-14': ['Exaltação da Santa Cruz'],
        '9-15': ['Nossa Senhora das Dores'],
        '9-16': ['Cornélio papa', 'Cipriano de Cartago'],
        '9-17': ['Roberto Belarmino', 'Hildegardes de Bingen'],
        '9-19': ['Januário de Benevento'],
        '9-20': ['André Kim Taegon', 'Paulo Chong Hasang'],
        '9-21': ['Mateus evangelista'],
        '9-23': ['Pio de Pietrelcina'],
        '9-26': ['Cosme mártir', 'Damião mártir'],
        '9-27': ['Vicente de Paulo'],
        '9-28': ['Wenceslau de Boêmia', 'Lourenço Ruiz'],
        '9-29': ['Miguel arcanjo', 'Gabriel arcanjo', 'Rafael arcanjo'],
        '9-30': ['Jerônimo de Estridão'],

        /* ── Outubro ────────────────────────────────────────── */
        '10-1': ['Teresa de Lisieux'],
        '10-2': ['Santos Anjos da Guarda'],
        '10-4': ['Francisco de Assis'],
        '10-5': ['Faustina Kowalska'],
        '10-6': ['Bruno de Colônia'],
        '10-7': ['Nossa Senhora do Rosário'],
        '10-9': ['Dionísio de Paris', 'João Leonardi'],
        '10-11':['João XXIII papa'],
        '10-14':['Calisto I papa'],
        '10-15':['Teresa de Ávila'],
        '10-16':['Hedwig da Silésia', 'Margarida Maria Alacoque'],
        '10-17':['Inácio de Antioquia'],
        '10-18':['Lucas evangelista'],
        '10-19':['João de Brébeuf', 'Isaac Jogues', 'Paulo da Cruz'],
        '10-22':['João Paulo II papa'],
        '10-23':['João de Cápua'],
        '10-24':['Antônio Maria Claret'],
        '10-28':['Simão apóstolo zelote', 'Judas Tadeu apóstolo'],

        /* ── Novembro ───────────────────────────────────────── */
        '11-1': ['Todos os Santos'],
        '11-3': ['Martinho de Porres'],
        '11-4': ['Carlos Borromeo'],
        '11-9': ['Dedicação da Basílica de Latrão'],
        '11-10':['Leão Magno'],
        '11-11':['Martinho de Tours'],
        '11-12':['Josafá de Polotsk'],
        '11-15':['Alberto Magno'],
        '11-16':['Gertrudes a Grande', 'Margarida da Escócia'],
        '11-17':['Isabel da Hungria'],
        '11-21':['Apresentação de Maria no Templo'],
        '11-22':['Cecília de Roma'],
        '11-23':['Clemente I papa', 'Columba'],
        '11-24':['André Dung-Lac'],
        '11-30':['André apóstolo'],

        /* ── Dezembro ───────────────────────────────────────── */
        '12-3': ['Francisco Xavier'],
        '12-4': ['João Damasceno'],
        '12-6': ['Nicolau de Mira'],
        '12-7': ['Ambrósio de Milão'],
        '12-8': ['Imaculada Conceição de Maria'],
        '12-9': ['Juan Diego'],
        '12-11':['Dâmaso I papa'],
        '12-12':['Nossa Senhora de Guadalupe'],
        '12-13':['Lúcia de Siracusa'],
        '12-14':['João da Cruz'],
        '12-21':['Pedro Canísio'],
        '12-23':['João de Kenty'],
        '12-25':['Natal do Senhor Jesus Cristo'],
        '12-26':['Estevão proto-mártir'],
        '12-27':['João evangelista apóstolo'],
        '12-28':['Santos Inocentes mártires'],
        '12-29':['Tomás Becket'],
        '12-31':['Silvestre I papa']
    };

})();
